export const historyTopics = ["The Real Story Behind the Trojan Horse",
    "The Mystery of the Lost City of Atlantis",
    "Secrets of the Pyramids: How Were They Built?",
    "The Black Death: How a Plague Changed the World",
    "The Rise and Fall of Ancient Rome in 60 Seconds",
    "Cleopatra: The Queen Who Seduced an Empire",
    "The True Story Behind the Salem Witch Trials",
    "How Genghis Khan Conquered the World",
    "The Dark History of the Spanish Inquisition",
    "Napoleon's Final Battle: What Went Wrong?",
    "The Mysterious Death of Alexander the Great",
    "Ancient Egypt’s Curses: Fact or Fiction?",
    "How the Vikings Really Lived (Not Like in Movies!)",
    "The Truth About Christopher Columbus",
    "The French Revolution: Why It Was So Brutal",
    "Spies of WWII: The Stories You’ve Never Heard",
    "The Titanic: What Really Happened That Night",
    "How the Mongols Shaped Modern Warfare",
    "The Untold History of the Great Wall of China",
    "How the Berlin Wall Changed History",
    "The Sinking of the Lusitania: Prelude to World War I",
    "The Forgotten Queens of Ancient Egypt",
    "The Real Pirates of the Caribbean",
    "The Rise of Adolf Hitler: A Timeline",
    "The Fall of Constantinople: End of an Era",
    "How the Samurai Lived: Facts vs. Myths",
    "Inside the Mind of Julius Caesar",
    "The True Story of Joan of Arc",
    "How Rasputin Influenced Russian History",
    "Who Was the Real Jack the Ripper?",
    "The Rise and Fall of the Aztec Empire",
    "The Secret Societies that Shaped History",
    "The Golden Age of Piracy: Real Treasure Hunters",
    "How the Printing Press Revolutionized the World",
    "The Spanish Armada’s Last Stand",
    "The Mysterious Disappearance of the Roanoke Colony",
    "How Did the Industrial Revolution Change the World?",
    "Ancient Greek Myths That Are Actually True",
    "The Mysterious Voyages of Zheng He",
    "The Brutal History of the Gladiators",
    "The Mayan Calendar: Did It Really Predict the End?",
    "How the Renaissance Changed Art Forever",
    "The Codebreakers of WWII: Heroes You’ve Never Heard Of",
    "The Deadliest Battles in History",
    "Spartacus: The Slave Who Led a Revolution",
    "The Real History Behind 'The Prince' by Machiavelli",
    "The Siege of Stalingrad: The Turning Point of WWII",
    "The Wild West: Fact vs. Hollywood",
    "Anne Boleyn: The Queen Who Lost Her Head",
    "The History of the Forbidden City in China",
    "Why the Roman Empire Fell: 5 Big Reasons",
    "Who Was the Real Robin Hood?",
    "The Mystery of King Tutankhamun’s Tomb",
    "Why Did the Ottoman Empire Last 600 Years?",
    "The Assassination of Archduke Franz Ferdinand",
    "The Battle of Thermopylae: 300 vs. the World",
    "Marie Antoinette: What Really Happened to Her?",
    "The Rise of the British Empire: How Did They Do It?",
    "The Real Story of Pocahontas",
    "The Mysterious Easter Island Statues",
    "How the Wright Brothers Invented the Airplane",
    "The Last Samurai: The Real Story",
    "The History of the Knights Templar",
    "The Code of Hammurabi: World’s First Law Code",
    "How the Spice Trade Changed the World",
    "The Bloodiest Day in American History: Antietam",
    "The Real Story Behind the Boston Tea Party",
    "The History of the Eiffel Tower: A Controversial Icon",
    "The Life and Death of Malcolm X",
    "The Legendary Tale of Beowulf",
    "How the Vikings Discovered America",
    "Queen Elizabeth I’s Secret Spy Network",
    "The Story Behind the Great Chicago Fire",
    "The Cuban Missile Crisis: How Close We Came to War",
    "How the Pharaohs of Egypt Ruled the Nile",
    "The True History of the Alamo",
    "The Tragic Story of the Donner Party",
    "The Assassination of Julius Caesar: Who Was Behind It?",
    "How the U.S. Won Its Independence",
    "The Secrets of Leonardo da Vinci’s Notebooks",
    "The Legendary Curse of the Hope Diamond",
    "Who Were the Conquistadors Really?",
    "Why the Hindenburg Disaster Changed Air Travel Forever",
    "How the Silk Road Connected the Ancient World",
    "The Story of the First Thanksgiving",
    "How Rome Built Its Empire: Engineering Marvels",
    "The Battle of Waterloo: Napoleon’s Final Defeat",
    "Who Was the Real Dracula?",
    "The Mysterious Death of Marilyn Monroe",
    "The Cold War: How a Spy Network Shaped History",
    "The Truth Behind Rasputin’s Murder",
    "Why the Great Depression Happened",
    "The Day the Stock Market Crashed: 1929 Explained",
    "The Secret Plans of the Manhattan Project",
    "The Life of Genghis Khan: How He Changed the World",
    "The Dark History of the Opium Wars",
    "How the Allies Won WWII: A Timeline",
    "The Story of the Suffragettes: How Women Won the Vote",
    "The Forgotten History of the Harlem Renaissance",
    "The Viking Siege of Paris: A City Under Attack",
    "How Nelson Mandela Ended Apartheid",
    "How Ancient Romans Partied: Wild Festivals and Feasts",
    "The Truth About the Spanish Civil War",
    "The Aztecs’ Human Sacrifices: Why They Did It",
    "How Pablo Escobar Built His Empire",
    "The Tragic Death of Princess Diana: What Happened?",
    "The Rise of Kim Dynasty in North Korea",
    "How the Apollo 11 Moon Landing Happened",
    "How the CIA Overthrew Governments During the Cold War",
    "The Deadliest Earthquakes in History",
    "Why the U.S. Civil War Was Inevitable",
    "The Life of Attila the Hun: Scourge of Rome",
    "How the Bolsheviks Took Power in Russia",
    "The Assassination of Abraham Lincoln: What Really Happened",
    "The History of Hollywood: The Golden Age of Cinema",
    "The Brutal History of the Spanish Conquistadors",
    "The Space Race: How the Cold War Went to Space",
    "The Untold History of the Underground Railroad",
    "The Burning of the Library of Alexandria: What Was Lost?",
    "The Real History Behind the Movie ‘Gladiator’",
    "How the Ancient Olympics Were Very Different from Today",
    "The Salem Witch Trials: Causes and Consequences",
    "The Sinking of the Titanic: Engineering Flaws?",
    "The Mongol Empire’s Invasion of Europe",
    "The History of Alcohol Prohibition in the U.S.",
    "How the Great Fire of London Changed the City",
    "The History of the Russian Czars",
    "The Untold Story of Harriet Tubman",
    "The End of the Samurai: How Japan Changed",
    "How Stonehenge Was Built: Theories Explained",
    "How the Dutch East India Company Dominated Trade",
    "How the First Computers Were Built in WWII",
    "The Code of the Samurai: Bushido Explained",
    "The Mystery of the Bermuda Triangle",
    "The Apollo 13 Mission: NASA’s Greatest Rescue",
    "The Story Behind the Great Wall of China",
    "Why the Vietnam War Was So Controversial",
    "The Rise of the Nazis: How It All Began",
    "The Great Emu War: Australia’s Strangest Battle",
    "The Dark History of the Atlantic Slave Trade",
    "How the Suffragettes Fought for Women’s Rights",
    "The History of the Rosetta Stone: Cracking Ancient Egypt",
    "How the Inca Empire Fell to Just a Few Hundred Men",
    "The Great Exhibition of 1851: The Birth of Modernity",
    "Why the Korean War Was the Forgotten War",
    "The First Crusade: A Journey to the Holy Land",
    "The History of Gunpowder and How It Changed War",
    "The Life of Catherine the Great",
    "Who Really Discovered America?",
    "The Story of the Trojan War: Myth or History?",
    "How the Bay of Pigs Invasion Failed",
    "The Secret History of the Freemasons",
    "The Life of Marie Curie: A Scientist Against All Odds",
    "The History of the Samurai Sword",
    "How the Silk Road Spread Ideas and Disease",
    "The Scandal of Watergate Explained",
    "The Most Daring Heists in History",
    "The Strange Life of Nikola Tesla",
    "Why the Berlin Wall Was Built and How It Fell",
    "The Scary Truth About Medieval Medicine",
    "The Deadliest Pandemics in History",
    "How Pearl Harbor Changed the Course of WWII",
    "The Real Story of the American Civil Rights Movement",
    "Why the Roaring Twenties Were So Wild",
    "The Fall of the Roman Republic: Caesar’s Role",
    "The Siege of Leningrad: WWII’s Deadliest Siege",
    "How Hannibal Crossed the Alps with Elephants",
    "The Mysterious Death of the Romanovs",
    "How the Space Shuttle Challenger Disaster Happened",
    "How the Louisiana Purchase Changed America",
    "The Real History of Blackbeard the Pirate",
    "Who Was the Man in the Iron Mask?",
    "How Women Worked in WWII: The Forgotten Heroes",
    "The Brutal Reality of Medieval Castles",
    "The Rise of the Medici Family in Florence",
    "How Shakespeare Changed the English Language",
    "The Mystery of the Mary Celeste"]


export const mysteryTopics = ["The Bermuda Triangle: Planes and Ships That Vanished",
    "The Mystery of the Mary Celeste: Ghost Ship or Abandoned?",
    "Who Was Jack the Ripper? Theories Explained",
    "The Voynich Manuscript: The World's Most Mysterious Book",
    "The Dyatlov Pass Incident: What Really Happened?",
    "The Disappearance of Amelia Earhart: Where Did She Go?",
    "The Loch Ness Monster: Fact or Fiction?",
    "The Mysterious Case of the Sodder Children",
    "Who Killed the Black Dahlia? Unsolved Hollywood Murder",
    "The Zodiac Killer: Can He Ever Be Caught?",
    "The Lost Colony of Roanoke: What Happened to Them?",
    "The Tunguska Event: A Mysterious Explosion in Siberia",
    "The Wow! Signal: Did We Receive a Message from Aliens?",
    "The Mysterious Disappearance of Malaysia Airlines Flight MH370",
    "The Secret of Oak Island: Buried Treasure or Hoax?",
    "The Enigma of the Antikythera Mechanism: Ancient Computer?",
    "The Mystery of Stonehenge: How and Why Was It Built?",
    "The Mothman: Legend or Real Cryptid?",
    "The Death of Elisa Lam: What Really Happened in the Cecil Hotel?",
    "The Monster of the Andes: Who Was Pedro Lopez?",
    "Who Was D.B. Cooper? The Man Who Vanished Mid-Air",
    "The Mystery of the Somerton Man (Tamam Shud)",
    "The Secrets of the Nazca Lines in Peru",
    "Who Was the Axeman of New Orleans?",
    "The Unsolved Hinterkaifeck Murders",
    "The Mysterious Death of Edgar Allan Poe",
    "The Case of the Lead Masks: Brazil’s Unexplained Incident",
    "The Green Children of Woolpit: Alien Encounter?",
    "The Black Knight Satellite: Alien Spy or Space Junk?",
    "The Bennington Triangle: Vermont’s Own Bermuda Triangle",
    "The Mystery of the Devil’s Footprints",
    "How Did the Great Sphinx Lose Its Nose?",
    "Who Was the Man in the Iron Mask?",
    "The Phoenix Lights: Arizona’s UFO Sighting",
    "The Mystery of the Isdal Woman: Unidentified Spy?",
    "The Unsolved Mystery of the Circleville Letters",
    "The Vanishing of Frederick Valentich: UFO Encounter?",
    "The Case of the Moving Coffins in Barbados",
    "Where Did the Amber Room Disappear To?",
    "Who Built Gobekli Tepe and Why?",
    "The Lost City of Atlantis: Did It Ever Exist?",
    "The Mystery of Bigfoot: Sightings and Evidence",
    "The Mystery of the Lizard Man of Scape Ore Swamp",
    "Who Stole the Mona Lisa in 1911?",
    "The Disappearance of the Flannan Isles Lighthouse Keepers",
    "The Voyages of the Ghost Ship Octavius",
    "The Riddle of the Bloop: A Mysterious Ocean Sound",
    "The Lost Treasure of the Knights Templar",
    "The Mysterious Death of Tupac Shakur: Who Did It?",
    "The Case of the Taos Hum: Unexplained Sound Phenomenon",
    "Who Was the Somerton Man? The Tamam Shud Case Explained",
    "The Mystery of the Babushka Lady at JFK’s Assassination",
    "The Haunted Winchester Mystery House: Why So Many Doors?",
    "The Disappearance of Jim Thompson: The Silk King of Thailand",
    "The Anjikuni Lake Mystery: A Whole Village Vanishes",
    "The Mystery of the Piri Reis Map: Antarctica’s Secret?",
    "The Unexplained Tunguska Event: What Caused the Explosion?",
    "The Legend of Spring-Heeled Jack: Real or Imagined?",
    "The Mystery of Kaspar Hauser: The Boy with No Past",
    "The Fate of Flight 19: Lost in the Bermuda Triangle",
    "The Mysterious Death of Princess Diana",
    "The Philadelphia Experiment: Did the Navy Teleport a Ship?",
    "The Mystery of the Wow! Signal: Contact from Aliens?",
    "Who Was the Beast of Gévaudan?",
    "The Disappearance of Emanuela Orlandi: Vatican Mystery",
    "The Curse of the Hope Diamond: Fact or Superstition?",
    "The Secret of the Georgia Guidestones: Who Built Them?",
    "The Vanishing Village of Hoer Verde",
    "The Ghost Ship SS Ourang Medan: What Happened to the Crew?",
    "The Unsolved Mystery of the Texarkana Moonlight Murders",
    "The Missing Money Pit of Oak Island: Where's the Treasure?",
    "The Disappearance of the Beaumont Children",
    "The Curse of King Tutankhamun’s Tomb",
    "The Unexplained Rongo-Rongo Script of Easter Island",
    "The Mystery of the Dancing Plague of 1518",
    "Who Was the Iceman Ötzi? Solving a 5,000-Year-Old Murder",
    "The Unsolved YOGTZE Case: German Cold Case Mystery",
    "Who Was DB Cooper? The Infamous Plane Hijacker",
    "The Mystery of the Skystone: Is It a Gem from Space?",
    "The Dyatlov Pass Incident: Were They Attacked by Aliens?",
    "The Identity of the Zodiac Killer: Could It Be Solved?",
    "The Legend of the Jersey Devil: Real or Myth?",
    "The Mysterious Case of Jaryd Atadero: Missing in the Mountains",
    "The Mysterious Death of Natalie Wood: Accident or Murder?",
    "The Phantom Time Hypothesis: Did 300 Years of History Not Exist?",
    "The Mystery of the Overtoun Bridge Dog Suicides",
    "Who Was the Grinning Man? Mysterious Paranormal Figure",
    "The Voynich Manuscript: A Book Written in an Unknown Language",
    "The Case of the Pollock Twins: Evidence of Reincarnation?",
    "The Mysterious Disappearance of Lars Mittank",
    "The Keddie Cabin Murders: Unsolved and Disturbing",
    "Who Was the Ghost of Flight 401?",
    "The Mystery of the Great Blue Hole in Belize",
    "How Did Glenn Miller Vanish Without a Trace?",
    "The Disappearance of Dorothy Arnold: What Happened?",
    "Who Were the Secret Keepers of Rennes-le-Château?",
    "The Lost Treasure of Forrest Fenn: Has It Been Found?",
    "The Phantom Limbs Mystery: Why Do People Feel Them?",
    "The Death of Ricky McCormick: An Unsolved Code",
    "Who Was the Westfield Watcher?",
    "The Mystery of the Axeman’s Jazz",
    "The Case of the Silent Twins: Why Did They Stop Talking?",
    "The Disappearance of Maura Murray: A Modern-Day Mystery",
    "The Sudden Vanishing of Brian Shaffer: No Clues, No Trace",
    "The Mysterious Voynich Manuscript: Still Uncrackable?",
    "The Case of the Missing Sodder Children",
    "Who Was the Zodiac Killer? New Evidence",
    "The Cryptic Green Children of Woolpit",
    "The Mystery of the Green Fireballs in the Sky",
    "The Unsolved Glico-Morinaga Case: Japan’s Biggest Heist",
    "The Mysterious Georgia Guidestones",
    "The Bizarre Legend of the Wendigo",
    "The Disappearance of Asha Degree",
    "The Secret Nazi Base in Antarctica: Myth or Fact?",
    "Who Was the Ghost of Freddy Jackson?",
    "The Mysterious Disappearance of Flight 370",
    "The Unsolved Texarkana Moonlight Murders",
    "The Disappearance of Jean Spangler",
    "The Unsolved Case of the Chicago Tylenol Murders",
    "Why Did Edgar Allan Poe Die So Mysteriously?",
    "The Taos Hum: What Is That Strange Sound?",
    "Did the Nazis Really Build UFOs? The Legend of Die Glocke",
    "The Mysterious Sea Creatures of the Deep Ocean",
    "The Disappearance of Barbara Newhall Follett",
    "The Legend of the Skinwalker Ranch",
    "The Curse of the Bell Witch",
    "The Mysterious Death of Natalie Wood",
    "Who Was the Phantom of Heilbronn?",
    "The Dyatlov Pass Incident: Natural Disaster or Something Sinister?",
    "The Enigma of the Baltic Sea Anomaly",
    "The Hoia Baciu Forest: The World’s Most Haunted Forest",
    "The Case of the Green Children of Woolpit",
    "The Mystery of the Kecksburg UFO Crash",
    "The Disappearance of Brandon Swanson",
    "The Legend of the Chupacabra",
    "Who Was the Lady of the Dunes?",
    "The Unsolved Case of the Texarkana Phantom Killer",
    "The Mystery of the Black Dahlia",
    "How Did the Ancient Egyptians Move Giant Stones?",
    "The Haunted History of the Stanley Hotel",
    "The Great Kentucky Meat Shower: What Fell from the Sky?",
    "The Truth Behind the Phoenix Lights",
    "The Legend of El Chupacabra",
    "The Mystery of the Winchester House",
    "The Disappearance of Susan Powell",
    "The Black Hope Curse: Did a Housing Development Unleash Spirits?",
    "The Case of the Voynich Manuscript: An Ancient Puzzle",
    "The Unsolved Hinterkaifeck Murders",
    "The Case of the Mary Celeste: A Ghost Ship Mystery",
    "The Mysterious Death of David Stone",
    "The Mystery of the Ghost Ship Lady Lovibond",
    "The Disappearance of Heather Teague",
    "The Taos Hum: Can You Hear It?",
    "The Mysterious Hexham Heads: Haunted Stones?"]



export const didYouKnowTopics = ["Did You Know the Eiffel Tower Can Grow Over 6 Inches in Summer?",
    "Did You Know Cleopatra Lived Closer to the Moon Landing Than the Pyramids?",
    "Did You Know Napoleon Was Once Attacked by Rabbits?",
    "Did You Know Honey Never Spoils? Archaeologists Have Found 3,000-Year-Old Honey!",
    "Did You Know Sharks Have Been Around Longer Than Trees?",
    "Did You Know There’s a Secret Train Station Under the Waldorf Astoria Hotel?",
    "Did You Know the Shortest War in History Lasted Only 38 Minutes?",
    "Did You Know Some Turtles Breathe Through Their Butts?",
    "Did You Know Russia Has a Larger Surface Area Than Pluto?",
    "Did You Know There’s a 5,000-Year-Old Tree Still Alive Today?",
    "Did You Know the Roman Empire Once Used Urine as Mouthwash?",
    "Did You Know Bananas Are Technically Berries but Strawberries Aren’t?",
    "Did You Know Wombat Poop Is Cube-Shaped?",
    "Did You Know a Day on Venus Is Longer Than a Year on Venus?",
    "Did You Know There Are More Stars in the Universe Than Grains of Sand on Earth?",
    "Did You Know There’s a Place on Earth Where It Hasn’t Rained in Over 2 Million Years?",
    "Did You Know the Longest Hiccuping Spree Lasted 68 Years?",
    "Did You Know Octopuses Have Three Hearts?",
    "Did You Know Ancient Romans Used Crushed Mice as Toothpaste?",
    "Did You Know New York City Was Once the Capital of the United States?",
    "Did You Know a Group of Flamingos Is Called a ‘Flamboyance’?",
    "Did You Know the United States Has No Official Language?",
    "Did You Know You Can Hear the Difference Between Hot and Cold Water?",
    "Did You Know Hippos Sweat Red?",
    "Did You Know Giraffes Only Sleep About 30 Minutes a Day?",
    "Did You Know Queen Elizabeth II Was a Trained Mechanic During WWII?",
    "Did You Know an Astronaut’s Height Can Increase in Space?",
    "Did You Know the First Computer Was Invented in the 19th Century?",
    "Did You Know There Are More Bacteria Cells in Your Body Than Human Cells?",
    "Did You Know the Great Wall of China Isn’t Visible from Space?",
    "Did You Know Humans Share 60% of Their DNA with Bananas?",
    "Did You Know There's a Bioluminescent Beach Where the Ocean Glows?",
    "Did You Know Cows Have Best Friends and Get Stressed When They’re Apart?",
    "Did You Know There’s a Lake in Africa That Can Turn Animals into Stone?",
    "Did You Know Space Smells Like Burnt Steak?",
    "Did You Know Some Dinosaurs Were the Size of Chickens?",
    "Did You Know the Canary Islands Are Named After Dogs, Not Birds?",
    "Did You Know the Human Nose Can Detect Over 1 Trillion Scents?",
    "Did You Know There’s a Jellyfish That Can Live Forever?",
    "Did You Know the Average Cloud Weighs About 1 Million Pounds?",
    "Did You Know Viking Helmets Didn’t Actually Have Horns?",
    "Did You Know Your Stomach Lining Regenerates Every 3 to 4 Days?",
    "Did You Know Japan Has a Cat Island?",
    "Did You Know the World’s Quietest Room Can Drive You Crazy?",
    "Did You Know Sloths Can Hold Their Breath Longer Than Dolphins?",
    "Did You Know Shakespeare Invented More Than 1,700 Words?",
    "Did You Know There’s a Town in Norway Where It’s Illegal to Die?",
    "Did You Know Butterflies Taste with Their Feet?",
    "Did You Know Human Bones Are About Five Times Stronger Than Steel?",
    "Did You Know Earth Used to Be Purple?",
    "Did You Know Einstein’s Brain Was Stolen After His Death?",
    "Did You Know Sea Cucumbers Can Eject Their Organs to Escape Predators?",
    "Did You Know a Cockroach Can Live for Weeks Without Its Head?",
    "Did You Know a Day on Jupiter Lasts Less Than 10 Hours?",
    "Did You Know You Can’t Hum While Holding Your Nose?",
    "Did You Know the Empire State Building Has Its Own Zip Code?",
    "Did You Know There’s a Species of Jellyfish That’s Immortal?",
    "Did You Know There’s a Giant Garbage Patch in the Pacific Ocean Twice the Size of Texas?",
    "Did You Know Some Fungi Can Control the Minds of Insects?",
    "Did You Know the First-Ever Vending Machine Dispensed Holy Water?",
    "Did You Know Tomatoes Were Once Thought to Be Poisonous?",
    "Did You Know Lightning Strikes Earth 100 Times Every Second?",
    "Did You Know the Word ‘Salary’ Comes from Salt?",
    "Did You Know Elephants Are One of the Only Animals That Can Recognize Themselves in a Mirror?",
    "Did You Know a Bolt of Lightning Contains Enough Energy to Toast 100,000 Slices of Bread?",
    "Did You Know There’s Enough DNA in Your Body to Stretch from the Sun to Pluto and Back?",
    "Did You Know the Eiffel Tower Was Almost Moved to Canada?",
    "Did You Know Kangaroos Can’t Walk Backwards?",
    "Did You Know Peanuts Aren’t Nuts, They’re Legumes?",
    "Did You Know Polar Bear Fur Isn’t White—It’s Transparent?",
    "Did You Know Venus Is the Only Planet that Rotates Clockwise?",
    "Did You Know the Original Olympic Games Were Held in the Nude?",
    "Did You Know Antarctica Is the Largest Desert on Earth?",
    "Did You Know Avocados Are Berries?",
    "Did You Know An Octopus Has 9 Brains and Blue Blood?",
    "Did You Know Some Snakes Can Fly?",
    "Did You Know An Astronaut’s Footprints on the Moon Will Last for 100 Million Years?",
    "Did You Know the Shortest Commercial Flight Is Less Than 2 Minutes Long?",
    "Did You Know Bubble Wrap Was Originally Invented as Wallpaper?",
    "Did You Know Humans Are the Only Animals that Blush?",
    "Did You Know You Can’t Snore and Dream at the Same Time?",
    "Did You Know the Leaning Tower of Pisa Wasn’t Always Leaning?",
    "Did You Know the First Alarm Clock Could Only Ring at 4 AM?",
    "Did You Know Some Fish Can Walk on Land?",
    "Did You Know It Rains Diamonds on Saturn and Jupiter?",
    "Did You Know the Moon Is Moving Away from Earth at 1.5 Inches Per Year?",
    "Did You Know You’re More Likely to Be Killed by a Vending Machine Than a Shark?",
    "Did You Know the Eiffel Tower Was Supposed to Be Torn Down?",
    "Did You Know Bananas Glow Blue Under Blacklight?",
    "Did You Know Pigeons Can Tell the Difference Between Art Styles?",
    "Did You Know There’s a Cave in Mexico Full of Giant Crystals?",
    "Did You Know Birds Are Technically Dinosaurs?",
    "Did You Know the Average Human Will Walk the Equivalent of Three Times Around the World in Their Lifetime?",
    "Did You Know You Can’t Breathe and Swallow at the Same Time?",
    "Did You Know Sloths Can Take Up to a Month to Digest Food?",
    "Did You Know Mount Everest Can Grow by Half an Inch Every Year?",
    "Did You Know A Day on Mercury Lasts 1,408 Hours?",
    "Did You Know There’s an Underwater Waterfall in Mauritius?",
    "Did You Know An Owl’s Eyes Are Bigger Than Its Brain?",
    "Did You Know Vikings Used Urine to Start Fires?",
    "Did You Know the Largest Snowflake Ever Recorded Was 15 Inches Wide?",
    "Did You Know The Human Brain Can Generate Enough Electricity to Power a Lightbulb?",
    "Did You Know Octopuses Can Change Color in Their Sleep?",
    "Did You Know A Cloud Can Weigh More Than a Million Pounds?",
    "Did You Know Flamingos Are Pink Because of Their Diet?",
    "Did You Know Cats Can’t Taste Sweetness?",
    "Did You Know A Human Could Swim Through a Blue Whale’s Arteries?",
    "Did You Know You Can’t Hear a Scream in Space?",
    "Did You Know Spiders Can’t Fly, But Some Use Webs to Glide?",
    "Did You Know The Sahara Desert Used to Be a Lush Green Land?",
    "Did You Know Some Frogs Freeze and Then Thaw Back to Life?",
    "Did You Know Earth Is Hit by Over 100 Tons of Space Dust Daily?",
    "Did You Know Jellyfish Have Existed Longer Than Dinosaurs?",
    "Did You Know Lightning Strikes the Same Place Twice—A Lot?",
    "Did You Know All the Ants on Earth Weigh About as Much as All the Humans?",
    "Did You Know An Apple in the Fridge Can Help Keep Other Foods Fresh?",
    "Did You Know The Human Eye Can Detect Over 10 Million Colors?",
    "Did You Know Hot Water Freezes Faster Than Cold Water?",
    "Did You Know The Deepest Part of the Ocean Is Deeper Than Mount Everest Is Tall?",
    "Did You Know Humans Are Bioluminescent, But Our Eyes Can’t See It?",
    "Did You Know a Group of Hedgehogs is Called a 'Prickle'?",
    "Did You Know Kangaroos Use Their Tails Like a Fifth Leg?"]

export const randomTopics = [
    "The Science of Why We Get Déjà Vu",
    "Is Time Travel Possible? Theories Explained",
    "Why Do Cats Always Land on Their Feet?",
    "How Long Could You Survive on Just Water?",
    "Why Do We Dream? Theories You’ve Never Heard Of",
    "The Truth About Cursed Objects: Do They Really Exist?",
    "How Do Lie Detectors Work and Can You Beat Them?",
    "What Would Happen If the Earth Stopped Spinning?",
    "The Science of Lucid Dreaming: How You Can Control Your Dreams",
    "Why Do We Get Goosebumps? The Science Behind It",
    "Why Do We See Faces in Inanimate Objects?",
    "How Do Magicians Really Saw People in Half?",
    "What Would Happen if the Sun Suddenly Disappeared?",
    "How Do Roller Coasters Work Without Falling Off?",
    "Why Are Some People Left-Handed?",
    "Can You Really Live Inside a Video Game Like 'The Matrix'?",
    "What’s Inside a Black Hole? Theories on the Unknown",
    "The Science Behind Why Humans Love Music",
    "Why Are We Afraid of the Dark? Evolutionary Psychology",
    "How Does Hypnosis Work and Can It Really Control You?",
    "What Happens to Your Body in Space Without a Spacesuit?",
    "Why Do We Love Watching Horror Movies? The Psychology of Fear",
    "The Secret Language of Plants: How They 'Talk' to Each Other",
    "How Do Airlines Actually Manage to Avoid Crashes?",
    "The Mandela Effect: Why Do So Many People Remember Events Differently?",
    "What Is Dark Matter? The Most Mysterious Stuff in the Universe",
    "Why Do Dogs Tilt Their Heads When You Talk to Them?",
    "Can You Really Train Your Brain to Be Smarter?",
    "What’s the Science Behind Falling in Love?",
    "Why Do We Yawn and Why Is It Contagious?",
    "The Truth Behind Body Language: What Are You Really Saying?",
    "Why Do We Have Wisdom Teeth? Evolutionary Leftovers",
    "Why Does Spicy Food Make Your Mouth Burn?",
    "Can We Really Communicate with Dolphins?",
    "Why Do We Cry When We’re Happy?",
    "What Happens to Your Body When You Hold Your Breath?",
    "Why Do Some People Never Get Mosquito Bites?",
    "Can You Really Live Off-Grid in the Modern World?",
    "The Science of Procrastination: Why We Delay Things",
    "What Would Happen If All the Ice on Earth Melted?",
    "Can You Really Predict Someone’s Personality by Their Handwriting?",
    "Why Do We Forget Dreams So Quickly?",
    "Why Are Human Beings So Addicted to Social Media?",
    "The Science of Attraction: Why Are We Drawn to Certain People?",
    "Why Do Cats Purr? The Hidden Meanings Behind It",
    "How Does Your Body Know When It’s Time to Wake Up?",
    "Can You Really See the Great Wall of China from Space?",
    "What’s the Most Dangerous Animal on Earth?",
    "Why Do We Have Fingerprints? Their Strange Origins",
    "What If We Had No Moon? How Life on Earth Would Be Different",
    "Why Do We Have Nightmares? What Causes Them?",
    "How Do Whales Communicate Over Long Distances?",
    "Why Do Some People Remember Their Past Lives?",
    "How Does Aging Work? Can We Slow It Down?",
    "Can Sound Actually Kill You?",
    "How Do We Taste Food? The Science of Flavor",
    "Why Do Birds Migrate Such Long Distances?",
    "Can We Ever Really Achieve Immortality?",
    "What If You Could Upload Your Brain to a Computer?",
    "How Does Your Body Heal Itself? The Science of Regeneration",
    "Why Are Humans the Only Species That Cook Their Food?",
    "How Do Coral Reefs Build Massive Underwater Cities?",
    "Can Artificial Intelligence Really Become Conscious?",
    "What Would Happen If Gravity Suddenly Disappeared?",
    "Why Do People Believe in Conspiracy Theories?",
    "How Long Can a Human Actually Stay Awake?",
    "Why Do Some People Have Perfect Pitch?",
    "Can You Really Train Your Brain to Have a Photographic Memory?",
    "Why Are Some People More Ticklish Than Others?",
    "What Would Happen if We Used 100% of Our Brain Capacity?",
    "The Science of Why We Procrastinate",
    "Can You Really Tell When Someone Is Lying?",
    "What Happens to Your Body in Extreme Cold?",
    "Why Are There So Many Different Languages in the World?",
    "What Would Happen if Everyone on Earth Jumped at the Same Time?",
    "How Do Animals Know How to Migrate?",
    "Why Do We Have Earwax?",
    "How Do Mirrors Work? The Science of Reflection",
    "What’s the Deal with Deja Vu? Theories on Why It Happens",
    "Why Do We Feel Butterflies in Our Stomachs When We’re Nervous?",
    "Why Do People Say 'Bless You' When You Sneeze?",
    "Can You Really Die of a Broken Heart?",
    "Why Do We Sometimes Wake Up Right Before Our Alarm?",
    "What’s the Science Behind Food Cravings?",
    "Why Are Some People Night Owls and Others Early Birds?",
    "What Happens in Your Brain When You Laugh?",
    "Why Do Some People Like Cilantro While Others Hate It?",
    "How Do Planes Stay in the Air?",
    "Can You Really Change Your Eye Color Naturally?",
    "Why Do Some People Talk in Their Sleep?",
    "What Would Happen if You Fell Into a Volcano?",
    "Why Do People Blush? The Science Behind It",
    "How Do Fish Sleep Without Drowning?",
    "Can You Really Get Addicted to Your Phone?",
    "What Would Happen If You Lived on Another Planet?",
    "Why Do We Dream? The Most Popular Theories",
    "Can You Really Train Yourself to Wake Up Without an Alarm?",
    "Can You Really Tell Someone’s Personality by Their Zodiac Sign?",
    "How Do Tsunamis Form? The Science Behind Massive Waves",
    "Why Does Our Stomach Growl When We’re Hungry?",
    "What Would Happen If You Never Took a Shower?",
    "Why Do Some People Have Phobias?",
    "Why Are Roller Coasters So Addictive?",
    "Can You Really Increase Your IQ?",
    "Why Are People Afraid of Clowns?",
    "What Would Happen If the Internet Shut Down Worldwide?",
    "How Do Clouds Float When They’re So Heavy?",
    "Can Animals Really Predict Natural Disasters?",
    "Why Do Some People Sleepwalk?",
    "What Would Happen If All the Bees Died?",
    "Can You Really Hear the Ocean in a Seashell?",
    "Why Do We Get Brain Freeze from Cold Drinks?",
    "What Happens in Your Brain When You Get Goosebumps?",
    "Why Do We Get Random Itches?",
    "What Happens in the Brain During a Near-Death Experience?",
    "Can You Really Survive a Lightning Strike?",
    "How Do Polar Bears Stay Warm in Freezing Conditions?",
    "Why Do We Feel Fear? The Science Behind It",
    "How Does Your Brain Form Memories?",
    "What’s the Science Behind Being Left or Right Brained?",
    "Why Do We Get Sweaty Palms When We’re Nervous?",
    "What Happens When You Mix Diet Coke and Mentos?",
    "Why Are Some People Addicted to Thrill-Seeking?",
    "Why Do Some People Get Seasick and Others Don’t?",
    "How Do Submarines Dive and Surface Without Sinking?",
    "Can a Human Really Outrun a Bear?",
    "Why Do Some People Love the Smell of Gasoline?",
    "How Does Your Body Fight Off a Cold?",
    "Why Do We Lose Our Taste When We Have a Cold?",
    "Can You Really Train Your Brain to Be Happier?",
    "What Would Happen If You Were Born in Space?",
    "How Do Spiders Spin Such Perfect Webs?",
    "Why Are We So Fascinated by Magic Tricks?",
    "Why Do People Get Tattoos? The Psychology Behind It",
    "What’s the Science Behind Muscle Memory?",
    "Why Are Some People More Creative Than Others?",
    "How Does the Brain Process Pain?",
    "What’s the Science of How We Perceive Time?",
    "Why Do People Get Addicted to Shopping?",
    "Can You Really Learn While You Sleep?",
    "What Happens in Your Brain When You Meditate?",
    "Why Do Some People Remember Dreams More Vividly?",
    "How Do Eels Generate Electricity?",
    "What Would Happen If There Were No More Trees on Earth?",
    "Why Do People Sleep with Stuffed Animals?",
    "Can We Ever Prove the Existence of Parallel Universes?",
    "Why Are Some People More Afraid of Heights?",
    "How Does the Brain Solve Problems So Quickly?",
    "Can You Train Your Body to Need Less Sleep?",
    "Why Do We Laugh? The Science of Humor",
    "What’s the Science of Why Music Moves Us?",
    "Why Do We Feel Nervous Before Public Speaking?",
    "What Happens in the Brain During Intense Focus?",
    "Can You Really Control Your Heart Rate with Your Mind?",
    "Why Do We Get ‘Pins and Needles’?",
    "How Do Lasers Actually Work?",
    "How Do Dolphins Sleep Without Drowning?",
    "What’s the Science Behind Human Attraction?"]

export const catTopics = ["Why Do Cats Purr? The Hidden Meanings Behind the Sound",
    "Why Do Cats Knead with Their Paws?",
    "How Do Cats Always Land on Their Feet?",
    "Why Do Cats Love Boxes So Much?",
    "Can Cats Really See in the Dark?",
    "Why Do Cats Bring You 'Gifts' Like Dead Mice?",
    "What Does It Mean When a Cat Slow Blinks at You?",
    "Why Do Cats Knock Things Over?",
    "How Do Cats Communicate with Their Tail Movements?",
    "Why Do Some Cats Hate Water?",
    "What Does It Mean When a Cat Licks You?",
    "How High Can Cats Actually Jump?",
    "Do Cats Really Have Nine Lives?",
    "Why Do Cats Sleep So Much?",
    "How Do Cats Find Their Way Home from Miles Away?",
    "Why Do Cats Stare at You?",
    "Why Do Cats Hate Closed Doors?",
    "How Can You Tell If Your Cat Loves You?",
    "Why Do Cats Meow? Decoding Their Different Sounds",
    "How to Teach Your Cat Tricks: Yes, It’s Possible!",
    "Do Cats Dream? What Happens When They Sleep",
    "Why Do Cats Chirp at Birds?",
    "Can Cats Really Predict Weather Changes?",
    "Why Do Cats Chase Laser Pointers?",
    "What Does It Mean When a Cat Shows You Its Belly?",
    "How to Tell If Your Cat Is Happy: Signs to Look For",
    "Why Do Cats Like to Sit on Your Laptop?",
    "Can Cats Really Sense When You’re Sick?",
    "Why Do Cats Hide When They’re Not Feeling Well?",
    "How Do Cats Clean Themselves So Well?",
    "Why Do Cats Get the 'Zoomies'?",
    "Can Cats Recognize Their Own Name?",
    "Why Do Cats Love Being in High Places?",
    "How to Tell If Your Cat Is Stressed",
    "Why Do Cats Love to Scratch Furniture?",
    "Do Cats Remember Their Owners After a Long Time?",
    "Why Do Cats Have Whiskers and What Are They For?",
    "Can Cats Really Understand Human Emotions?",
    "How to Make Your Cat More Affectionate",
    "Why Do Cats Sometimes Bite When You Pet Them?",
    "Why Do Cats Roll on Their Back?",
    "How Do Cats Choose Their Favorite Person?",
    "Why Do Cats Wiggle Their Butts Before They Pounce?",
    "How Old Is Your Cat in Human Years?",
    "Do Cats Miss Their Owners?",
    "What’s the Science Behind Cat Naps?",
    "Why Do Cats Like to Rub Against You?",
    "Why Do Cats Stick Their Tongues Out?",
    "Can Cats Really Be Left-Handed or Right-Handed?",
    "Why Do Some Cats Have Extra Toes?",
    "What’s the History of Cats Being Worshiped in Ancient Egypt?",
    "Why Do Cats Cover Their Food with Their Paws?",
    "How Do Cats Always Know When It’s Mealtime?",
    "What Does It Mean When a Cat’s Ears Are Back?",
    "Why Do Cats Sleep in Weird Positions?",
    "How Do You Know If Your Cat Is Lonely?",
    "Why Do Cats Hate Vacuums?",
    "What’s the Science Behind Cat Purring and Human Healing?",
    "Why Do Cats Love Head-Butting?",
    "Can Cats Really Get Jealous?",
    "Why Do Cats Hide in Small Spaces?",
    "What Do Cats See When They Look in a Mirror?",
    "Why Do Cats Lick Each Other?",
    "Do Cats Understand Time? How Long Are They Really Gone?",
    "What Does It Mean When a Cat Twitches Its Tail?",
    "How Can You Tell If a Cat Is in Pain?",
    "Why Do Cats Sometimes Sleep on Your Face?",
    "How Do Cats Communicate with Each Other?",
    "Can Cats Really Sense Earthquakes?",
    "Why Do Some Cats Follow You Everywhere?",
    "How to Calm a Scared or Anxious Cat",
    "Why Do Cats Lick Their Fur So Much?",
    "Can Cats Get Depressed?",
    "How Do Cats Use Their Whiskers to Navigate?",
    "Why Do Some Cats Meow So Much?",
    "What’s the Best Way to Introduce a New Cat to Your Home?",
    "Why Do Cats Sometimes 'Fake' Bury Their Food?",
    "Why Do Cats Run Around at 3 AM?",
    "What Do Cats Think About Humans?",
    "Why Do Cats Sneeze? What’s Normal and What’s Not",
    "Can Cats Really Get Along with Dogs?",
    "Why Do Cats Like to Climb Trees?",
    "What Does It Mean When a Cat’s Tail Is Puffed Up?",
    "Why Do Cats Bite Their Own Tails?",
    "What Are the Benefits of Owning a Cat?",
    "How Do Cats Keep Themselves Cool in Hot Weather?",
    "Can Cats Recognize Themselves in a Mirror?",
    "Why Do Some Cats Have Different Colored Eyes?",
    "What’s the Story Behind Cats and Superstition?",
    "How Can You Tell If Your Cat Is Overweight?",
    "Do Cats Get Lonely When You’re Gone?",
    "Why Do Cats Sometimes Sleep With Their Eyes Open?",
    "What Are the Most Common Myths About Cats?",
    "How Do You Know If a Cat Is Purring Out of Happiness or Pain?",
    "Can Cats Really Talk Back to You?",
    "What’s the Best Way to Train a Cat?",
    "Why Do Cats Chase Their Own Tails?",
    "Can Cats Really Be Hypoallergenic?",
    "Why Do Some Cats Love Water?",
    "How to Create a Perfect Play Environment for Your Cat",
    "What’s the Most Playful Breed of Cat?",
    "Do Cats Get Bored Without Toys?",
    "Why Do Cats Always Seem So Curious?",
    "How Can You Tell If a Cat Is Angry?",
    "Can Cats See Ghosts? Why They Stare at Nothing",
    "Why Do Cats Like to Sit in the Sun?",
    "How Do Cats Use Their Sense of Smell?",
    "Why Do Cats Love Catnip So Much?",
    "What’s the Oldest Cat Breed in the World?",
    "Can Cats Really Communicate with Their Eyes?",
    "Why Do Some Cats Hiss for No Reason?",
    "How Do You Stop a Cat from Scratching the Furniture?",
    "Why Do Cats Sometimes Groom Their Owners?",
    "What’s the Science Behind Cats’ Night Vision?",
    "How Do Cats React to Music?",
    "What Does It Mean When a Cat Is Panting?",
    "Why Do Cats Like to Sleep in Tight Spaces?",
    "Can Cats Understand TV Shows or Videos?",
    "How Can You Help Your Cat Live Longer?",
    "Do Cats Know When You’re Upset?",
    "Why Do Cats Sometimes Ignore You?",
    "Can You Teach a Cat to Walk on a Leash?",
    "Why Do Cats Like High Places?",
    "What’s the Most Expensive Cat Breed?",
    "How Do Cats Handle Extreme Weather?",
    "Why Do Cats Groom Each Other?",
    "Can Cats Really Predict When Their Owners Are Coming Home?",
    "How to Help Your Cat Get Along with Other Pets",
    "Why Do Cats Sometimes Paw at Their Reflection?",
    "What Do Cats Do When You’re Not Home?",
    "Can You Really Train a Cat Like a Dog?",
    "Why Do Cats Sit on Your Things?",
    "How Do Cats Keep Their Balance?",
    "Why Do Cats Love Staring Out the Window?",
    "Can Cats Really Get Attached to One Person?",
    "Why Do Some Cats Have No Fur?",
    "Why Do Cats Sometimes Sleep in Their Litter Box?",
    "Do Cats Remember People They Met Years Ago?",
    "How Do Cats Show They Trust You?",
    "What’s the Science Behind Cats’ Sharp Reflexes?",
    "Why Do Cats Sometimes Lick Plastic?",
    "Can Cats Really See in Color?",
    "How Do Cats Stay So Clean Without Baths?",
    "Why Do Cats Follow You to the Bathroom?",
    "Why Do Cats Hide When They’re Playing?",
    "Can Cats Understand Human Speech?",
    "What Are the Best Cat Toys for Mental Stimulation?",
    "How Do Cats Learn New Behaviors?",
    "Why Do Cats Sometimes Lick Their Own Fur Off?",
    "What’s the Secret to a Long, Healthy Life for Your Cat?",
    "Why Do Cats Love Sleeping in Your Laundry?",
    "How Do Cats Know When It’s Time to Eat?",
    "Why Do Cats Sometimes 'Chatter' Their Teeth?",
    "What’s the Science Behind Cats’ Super Hearing?",
    "Why Do Cats Get Along Better with Certain People?",
    "How Do Cats Handle Stress?",
    "What Are the Health Benefits of Owning a Cat?",
    "Why Do Cats Sleep So Much More Than Dogs?",
    "Can Cats Recognize Themselves in Photos?",
    "How Do Cats Choose Where to Sleep?",
    "Why Do Cats Sometimes Sleep on Your Head?",
    "What’s the Story Behind Cats in Mythology?",
    "How Do Cats Comfort You When You’re Sick?",
    "Why Do Cats Chase Shadows?",
    "How Do Cats Adapt to New Environments?",
    "What’s the Difference Between a House Cat and a Wild Cat?",
    "Why Do Cats Sometimes Refuse to Eat?",
    "How Can You Tell If Your Cat Is Getting Enough Exercise?",
    "Why Do Cats Flick Their Ears So Much?",
    "Can Cats Understand Mirrors?",
    "Why Do Some Cats Love Belly Rubs and Others Don’t?",
    "Why Do Cats Love Sleeping on Clean Laundry?",
    "How Do Cats Use Their Whiskers to Navigate Tight Spaces?",
    "Can You Teach a Cat to Fetch?",
    "Why Do Cats Love to Watch Birds?",
    "Why Do Some Cats Purr Louder Than Others?"]

export const top5Topics = [
    "Top 5 Ancient Civilizations You’ve Never Heard Of",
    "Top 5 Most Mysterious Places on Earth",
    "Top 5 Most Dangerous Jobs in the World",
    "Top 5 Creepiest Unsolved Mysteries",
    "Top 5 Myths About the Bermuda Triangle",
    "Top 5 Secret Government Projects You Didn’t Know Existed",
    "Top 5 Most Haunted Places in the World",
    "Top 5 Conspiracy Theories That Turned Out to Be True",
    "Top 5 Ancient Lost Cities You Can Still Visit",
    "Top 5 Craziest Things Ever Found in the Ocean",
    "Top 5 Most Unbelievable Animal Friendships",
    "Top 5 Most Bizarre Phobias",
    "Top 5 Historical Events That Changed the World",
    "Top 5 Most Expensive Foods in the World",
    "Top 5 Most Luxurious Hotels in the World",
    "Top 5 Most Popular Dog Breeds of 2024",
    "Top 5 Famous Unsolved Murders in History",
    "Top 5 Most Dangerous Creatures in the Ocean",
    "Top 5 Craziest Weather Phenomena Ever Recorded",
    "Top 5 Famous Ghost Stories from Around the World",
    "Top 5 Best Natural Wonders to Visit Before You Die",
    "Top 5 Most Mysterious Disappearances in History",
    "Top 5 Richest People in History",
    "Top 5 Largest Animals That Ever Lived",
    "Top 5 Most Beautiful Places on Earth",
    "Top 5 Strangest Coincidences in History",
    "Top 5 Most Powerful Women in History",
    "Top 5 Most Bizarre Things Found in Space",
    "Top 5 Weirdest Laws from Around the World",
    "Top 5 Craziest Escape Stories in History",
    "Top 5 Worst Natural Disasters of All Time",
    "Top 5 Tallest Buildings in the World",
    "Top 5 Cutest Exotic Pets You Can Own",
    "Top 5 Most Dangerous Insects in the World",
    "Top 5 Places You Can’t Visit (And Why)",
    "Top 5 Rarest Animals on the Planet",
    "Top 5 Historical Figures with Crazy Life Stories",
    "Top 5 Most Expensive Cars in the World",
    "Top 5 Most Famous Art Heists",
    "Top 5 Longest Bridges in the World",
    "Top 5 Most Mysterious Underwater Ruins",
    "Top 5 Greatest Ancient Inventions Still Used Today",
    "Top 5 Most Legendary Swords in History",
    "Top 5 Biggest Scientific Breakthroughs of 2024",
    "Top 5 Strangest Things Sent into Space",
    "Top 5 Craziest Unsolved Heists",
    "Top 5 Most Dangerous Volcanoes in the World",
    "Top 5 Most Mysterious Books Ever Written",
    "Top 5 Most Bizarre World Records",
    "Top 5 Most Famous Animals in History",
    "Top 5 Craziest Coincidences That Actually Happened",
    "Top 5 Most Mysterious Sounds Ever Recorded",
    "Top 5 Famous Unsolved Art Mysteries",
    "Top 5 Strangest Foods People Actually Eat",
    "Top 5 Most Famous Plane Disappearances",
    "Top 5 Scariest Creatures in Mythology",
    "Top 5 Biggest Technology Trends of 2024",
    "Top 5 Most Expensive Cat Breeds",
    "Top 5 Most Bizarre Natural Phenomena",
    "Top 5 Most Amazing Sculptures Made from Ice",
    "Top 5 Most Mysterious Objects Found in the Ocean",
    "Top 5 Creepiest Abandoned Places in the World",
    "Top 5 Most Valuable Gems Ever Discovered",
    "Top 5 Deadliest Creatures in History",
    "Top 5 Most Infamous Spy Stories",
    "Top 5 Strangest Discoveries in Ancient Pyramids",
    "Top 5 Craziest Things Humans Have Ever Eaten",
    "Top 5 Most Iconic Fashion Trends of All Time",
    "Top 5 Most Mysterious Shipwrecks",
    "Top 5 Most Bizarre Traditions from Around the World",
    "Top 5 Creepiest Rituals Still Performed Today",
    "Top 5 Most Jaw-Dropping Movie Stunts Ever Performed",
    "Top 5 Strangest Weather Events Ever Recorded",
    "Top 5 Most Bizarre Conspiracy Theories",
    "Top 5 Most Famous Magic Tricks Explained",
    "Top 5 Most Valuable Collectibles Ever Sold",
    "Top 5 Strangest Laws Still in Effect Today",
    "Top 5 Most Mysterious Space Signals Ever Detected",
    "Top 5 Most Haunted Hotels You Can Stay In",
    "Top 5 Craziest Scientific Experiments Ever Conducted",
    "Top 5 Most Popular Cat Breeds of 2024",
    "Top 5 Most Amazing Natural Light Phenomena",
    "Top 5 Most Expensive Mansions in the World",
    "Top 5 Strangest Ancient Artifacts Ever Discovered",
    "Top 5 Most Unbelievable Survival Stories",
    "Top 5 Most Dangerous Criminals in History",
    "Top 5 Most Famous Supernatural Encounters",
    "Top 5 Most Bizarre Historical Coincidences",
    "Top 5 Most Mysterious Lost Artifacts",
    "Top 5 Most Famous Paintings with Hidden Meanings",
    "Top 5 Weirdest Museums You Can Visit",
    "Top 5 Most Dangerous Jobs in History",
    "Top 5 Strangest Animal Adaptations",
    "Top 5 Most Famous Historical Figures You Didn’t Know Were Related",
    "Top 5 Craziest Inventions That Changed the World",
    "Top 5 Most Fascinating Ancient Monuments You Can Visit",
    "Top 5 Most Expensive Items Ever Sold at Auction",
    "Top 5 Most Shocking Celebrity Scandals of All Time"];

export const urbanLegendsTopics = ["The Legend of the Mothman: Creature of West Virginia",
    "The Creepy Tale of Slender Man: How It Spread",
    "The Urban Legend of Bloody Mary: The Truth Behind the Mirror",
    "The Chilling Story of The Black-Eyed Children",
    "The Vanishing Hitchhiker: The Classic Ghost Story",
    "The Legend of La Llorona: Mexico’s Weeping Woman",
    "The Goatman of Maryland: Fact or Fiction?",
    "The Killer in the Backseat: A Terrifying Urban Legend",
    "The Legend of the Bunny Man Bridge",
    "The Legend of Kuchisake-Onna: Japan’s Slit-Mouthed Woman",
    "The Jersey Devil: A Creature that Roams the Pine Barrens",
    "The Legend of the Bell Witch: A Haunted Family in Tennessee",
    "The Phantom of the Highways: The Ghostly Hitchhiker",
    "The Creepy Tale of the Russian Sleep Experiment",
    "The Legend of the Wendigo: A Cannibal Spirit in the Forest",
    "The Legend of the Hook Man: A Classic Campfire Tale",
    "The Chupacabra: The Blood-Sucking Creature of Legend",
    "The Legend of Cropsey: The Real Boogeyman",
    "The Legend of the Vanishing Hotel Room",
    "The Curse of the Crybaby Bridge",
    "The Tale of the Midnight Game: A Ritual You Should Never Try",
    "The Legend of the Licked Hand: A Dog or a Killer?",
    "The Urban Legend of Polybius: The Cursed Arcade Game",
    "The Legend of Teke Teke: Japan’s Urban Ghost",
    "The Babysitter and the Man Upstairs: The Call Came from Inside the House",
    "The Legend of the Sewer Alligators in New York City",
    "The Smiling Man: A Creepy Encounter",
    "The Legend of the Haunted Clown Doll",
    "The Legend of the Green Man (Charlie No-Face)",
    "The Legend of the Crooked Man: Is He Real?",
    "The Urban Legend of the 'Killer' Chain Emails",
    "The Legend of the Mysterious Melon Heads",
    "The Legend of the Dog Boy of Arkansas",
    "The Haunted Legend of Helltown, Ohio",
    "The Legend of the Skinwalkers: Shapeshifting Creatures of Navajo Lore",
    "The Legend of the White Lady Ghost",
    "The Legend of the Elevator Game: Entering Another World",
    "The Legend of Pigman Road",
    "The Legend of the Fresno Nightcrawlers",
    "The Tale of the Headless Horseman",
    "The Legend of the Banshee: Ireland’s Wailing Spirit",
    "The Tale of the Faceless Woman",
    "The Legend of Robert the Doll: The Real-Life Chucky",
    "The Legend of the Vanishing Twin: A Spooky Medical Tale",
    "The Legend of El Silbón: The Whistling Ghost of Venezuela",
    "The Legend of the Slaughterhouse Canyon",
    "The Curse of the Crying Boy Painting",
    "The Legend of the 'Rake' Creature",
    "The Tale of the Phantom Killer of Texarkana",
    "The Legend of the Grinning Man: Who Is He?",
    "The Tale of the Red Room: The Deadly Internet Urban Legend",
    "The Legend of the Hand of Glory: A Gruesome Artifact",
    "The Legend of 'The Watcher' House",
    "The Tale of the Death Car on Archer Avenue",
    "The Legend of the Screaming Tunnel",
    "The Legend of the Shadow People: Creepy Encounters",
    "The Tale of the Cursed VHS Tape",
    "The Legend of the Devil’s Tree in New Jersey",
    "The Curse of the Little Bastard: James Dean’s Haunted Car",
    "The Legend of the Dog-Headed Men",
    "The Tale of the Blind Maiden Website",
    "The Legend of the Woman in White: A Global Ghost Story",
    "The Legend of the Boogeyman: Different Versions Around the World",
    "The Legend of the Midnight Man Ritual",
    "The Tale of the Doppelgänger: Evil Twins or Bad Omens?",
    "The Legend of the Lady in Red: A Haunting Beauty",
    "The Creepy Tale of the Slaughterhouse Five House",
    "The Urban Legend of the Crying Statue",
    "The Legend of the Grim Reaper: Death’s Messenger",
    "The Tale of the Hitchhiking Phantom Bride",
    "The Legend of the Gurdon Light",
    "The Haunted Tale of the Queen Mary Ship",
    "The Urban Legend of the Organ Thieves",
    "The Tale of the Phantom of Overton Bridge",
    "The Legend of the Vanishing Ships in the Bermuda Triangle",
    "The Story of Annabelle: The Haunted Doll",
    "The Legend of the Phantom Train",
    "The Legend of the Knock Knock Road Ghost",
    "The Urban Legend of the Midnight Man Challenge",
    "The Legend of the Blair Witch: Fact or Fiction?",
    "The Tale of the Haunted Oak Tree",
    "The Legend of the Donkey Lady Bridge",
    "The Haunted Legend of Resurrection Mary",
    "The Story of the Curse of the Pharaohs",
    "The Legend of the Poisoned Halloween Candy",
    "The Urban Legend of the Dead Body Under the Hotel Bed",
    "The Tale of the Haunted Chessboard",
    "The Legend of the Ghost Trains of Alabama",
    "The Tale of the Ghostly Boy on the School Bus",
    "The Legend of the Dark Watchers in California",
    "The Story of the Haunted Winchester Mystery House",
    "The Legend of the Fearsome Slide-Rock Bolter",
    "The Urban Legend of the Slit-Faced Woman",
    "The Haunted Tale of the Screaming Staircase",
    "The Legend of the Snallygaster: A Monster of Maryland",
    "The Tale of the Bermuda Triangle's Missing Planes",
    "The Legend of the Phantom Cat",
    "The Tale of the Electric Chair Ride Urban Legend",
    "The Legend of the Disappearing Campers",
    "The Urban Legend of 'Dead Man’s Curve'",
    "The Legend of the Hook-Handed Killer",
    "The Creepy Tale of the Highway Phantom Hitchhiker"]


export const allTopics = [historyTopics, mysteryTopics, randomTopics, didYouKnowTopics, catTopics, top5Topics, urbanLegendsTopics]